package com.ericg.kripto.presentation.theme

import androidx.compose.ui.graphics.Color


val DarkGray = Color(0xFF202020)
val MediumGray = Color(0xFF505050)
val ColorPrimary = Color(0xFF122E4E)
val TextWhite = Color(0xFFEEEEEE)
val ColorDormantBg = Color(0XFFFFECEC)
val ColorDormant = Color(0xFF122E4E).copy(alpha = 0.56F)
val ColorBadgeBg = Color(0XFF039800).copy(alpha = 0.12F)
val ColorBadgeText = Color(0xFF027600)
val ColorLinkDark = Color(0xFF60A0FF)
val ColorOrangeDark = Color(0xFFFF9517)

val md_theme_dark_primary = Color(0xFFFFB945)
val md_theme_dark_onPrimary = Color(0xFF452B00)
val md_theme_dark_primaryContainer = Color(0xFF624000)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDAE)
val md_theme_dark_secondary = Color(0xFFDDC3A2)
val md_theme_dark_onSecondary = Color(0xFF3E2E16)
val md_theme_dark_secondaryContainer = Color(0xFF56442B)
val md_theme_dark_onSecondaryContainer = Color(0xFFFADEBC)
val md_theme_dark_tertiary = Color(0xFFB8CEA2)
val md_theme_dark_onTertiary = Color(0xFF243516)
val md_theme_dark_tertiaryContainer = Color(0xFF3A4C2B)
val md_theme_dark_onTertiaryContainer = Color(0xFFD3EABC)
val md_theme_dark_error = Color(0xFFFFB4A9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD4)
val md_theme_dark_background = Color(0xFF1F1B16)
val md_theme_dark_onBackground = Color(0xFFEAE1D9)
val md_theme_dark_surface = Color(0xFF1F1B16)
val md_theme_dark_onSurface = Color(0xFFEAE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF4F4539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3C4B4)
val md_theme_dark_outline = Color(0xFF9C8F80)
val md_theme_dark_inverseOnSurface = Color(0xFF32281A)
val md_theme_dark_inverseSurface = Color(0xFFEAE1D9)
val md_theme_dark_inversePrimary = Color(0xFF624000)

val md_theme_light_primary = Color(0xFF825500)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDAE)
val md_theme_light_onPrimaryContainer = Color(0xFF2A1800)
val md_theme_light_secondary = Color(0xFF6F5B40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFADEBC)
val md_theme_light_onSecondaryContainer = Color(0xFF271904)
val md_theme_light_tertiary = Color(0xFF516440)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD3EABC)
val md_theme_light_onTertiaryContainer = Color(0xFF102004)
val md_theme_light_error = Color(0xFFBA1B1B)
val md_theme_light_errorContainer = Color(0xFFFFDAD4)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFFCFCFC)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFFCFCFC)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFF0E0CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4F4539)
val md_theme_light_outline = Color(0xFF817567)
val md_theme_light_inverseOnSurface = Color(0xFFF9EFE6)
val md_theme_light_inverseSurface = Color(0xFF34302A)
val md_theme_light_inversePrimary = Color(0xFFFFB945)